plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.google.guava:guava:31.1-jre'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

application {
    mainClass = 'ShoppingCartMain'
}

sourceSets {
    main {
        java {
            srcDirs = ['app/src/main/java']
        }
        resources {
            srcDirs = ['app/src/main/resources']
        }
    }
    test {
        java {
            srcDirs = ['app/src/test/java']
        }
        resources {
            srcDirs = ['app/src/test/resources']
        }
    }
}

task generateJavadocs(type: Javadoc) {
    source = sourceSets.main.allJava
    destinationDir = file("./docs")
}

jar {
    manifest {
        attributes(
            'Main-Class': 'ShoppingCartMain'
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}